// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace administracionUsuarios.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("administracionUsuarios.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("idUsuarioCreacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("administracionUsuarios.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("idUsuarioCreacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("administracionUsuarios.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("IdCargo")
                        .HasColumnType("int")
                        .HasColumnName("idCargo");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int")
                        .HasColumnName("idDepartamento");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("primerApellido");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("primerNombre");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("segundoApellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("segundoNombre");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("administracionUsuarios.Models.User", b =>
                {
                    b.HasOne("administracionUsuarios.Models.Cargo", "IdCargoNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdCargo")
                        .HasConstraintName("FK__users__idCargo__29572725");

                    b.HasOne("administracionUsuarios.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdDepartamento")
                        .HasConstraintName("FK__users__idDeparta__286302EC");

                    b.Navigation("IdCargoNavigation");

                    b.Navigation("IdDepartamentoNavigation");
                });

            modelBuilder.Entity("administracionUsuarios.Models.Cargo", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("administracionUsuarios.Models.Departamento", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
